### PR TITLE
Initial 5.0 migrate attempt

### PR DESCRIPTION
**Pull request by matthewdickinson**
This is an initial attempt at migrating to Strapi 5. There may be pieces no longer needed, but it is working as of now.

I see that on the Field Add page (in Dark Mode), the color of the Component title is wrong, but it's usable and everything else seems to work appropriately.

### CODE REVIEW

**Comment by hanpaine** [comment]
Hey @matthewdickinson - just spotted this PR you raised back in July :) I'd recommend re-trying now, the code will have moved a lot but is now in a stable position. Please do let us know if you have questions or feedback during the migration. There is some guidance here too: https://docs-next.strapi.io/dev-docs/migration/v4-to-v5/additional-resources/plugins-migration 
Cheers!

**Review by matar360 — APPROVED** [review]

**Comment by btnalexandre** [comment]
Thank you so much for your PR.

If anyone wants to update the plugin in their Strapi until this PR is merged by the author, they can run this:

> npm install matthewdickinson/strapi-plugin-multi-select#strapi_5 

or for `pnpm` :

> pnpm add matthewdickinson/strapi-plugin-multi-select#strapi_5

**Comment by gavgrego** [comment]
Excellent, was going to fork and make the changes via migration guide myself, but this works, thank you.

**Comment by monolithed** [comment]
@matthewdickinson, thank you for your work, but I'm still having trouble resolving the dependencies. I'm trying to install your RP on a freshly installed version of Strapi.

```
➜ npm install matthewdickinson/strapi-plugin-multi-select#strapi_5
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! Found: react-select@5.8.0
npm ERR! node_modules/react-select
npm ERR!   react-select@"5.8.0" from @strapi/admin@5.0.2
npm ERR!   node_modules/@strapi/admin
npm ERR!     peer @strapi/admin@"^5.0.0 || ^5.0.0-beta || ^5.0.0-alpha || ^5.0.0-rc" from @strapi/content-manager@5.0.2
npm ERR!     node_modules/@strapi/content-manager
npm ERR!       peer @strapi/content-manager@"^5.0.0" from @strapi/content-releases@5.0.2
npm ERR!       node_modules/@strapi/content-releases
npm ERR!         @strapi/content-releases@"5.0.2" from @strapi/strapi@5.0.2
npm ERR!         node_modules/@strapi/strapi
npm ERR!       3 more (@strapi/i18n, @strapi/review-workflows, @strapi/strapi)
npm ERR!     peer @strapi/admin@"^5.0.0" from @strapi/content-releases@5.0.2
npm ERR!     node_modules/@strapi/content-releases
npm ERR!       @strapi/content-releases@"5.0.2" from @strapi/strapi@5.0.2
npm ERR!       node_modules/@strapi/strapi
npm ERR!         peer @strapi/strapi@"^5.0.0 || ^5.0.0-beta || ^5.0.0-alpha || ^5.0.0-rc" from @strapi/plugin-cloud@5.0.2
npm ERR!         node_modules/@strapi/plugin-cloud
npm ERR!         2 more (@strapi/plugin-users-permissions, the root project)
npm ERR!     7 more (@strapi/content-type-builder, @strapi/core, ...)
npm ERR!   react-select@"5.8.0" from @strapi/upload@5.0.2
npm ERR!   node_modules/@strapi/upload
npm ERR!     @strapi/upload@"5.0.2" from @strapi/strapi@5.0.2
npm ERR!     node_modules/@strapi/strapi
npm ERR!       peer @strapi/strapi@"^5.0.0 || ^5.0.0-beta || ^5.0.0-alpha || ^5.0.0-rc" from @strapi/plugin-cloud@5.0.2
npm ERR!       node_modules/@strapi/plugin-cloud
npm ERR!         @strapi/plugin-cloud@"5.0.2" from the root project
npm ERR!       2 more (@strapi/plugin-users-permissions, the root project)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! strapi-plugin-multi-select@"matthewdickinson/strapi-plugin-multi-select#strapi_5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-select@5.7.0
npm ERR! node_modules/react-select
npm ERR!   peer react-select@"5.7.0" from strapi-plugin-multi-select@2.0.0
npm ERR!   node_modules/strapi-plugin-multi-select
npm ERR!     strapi-plugin-multi-select@"matthewdickinson/strapi-plugin-multi-select#strapi_5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

Here're my dependencies:

```
{
  "dependencies": {
    "@strapi/plugin-cloud": "5.0.2",
    "@strapi/plugin-users-permissions": "5.0.2",
    "@strapi/strapi": "5.0.2",
    "better-sqlite3": "9.4.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  }
}
````

```
➜ npm ls react-select
yadga@0.1.0 /Users/monolithed/workspace/shepol/strapi
└─┬ @strapi/strapi@5.0.2
  ├─┬ @strapi/admin@5.0.2
  │ └── react-select@5.8.0
  └─┬ @strapi/upload@5.0.2
    └── react-select@5.8.0 deduped
```

The problem is here: "react-select": "5.7.0",

**Comment by monolithed** [comment]
```
npm install matthewdickinson/strapi-plugin-multi-select#strapi_5 --legacy-peer-deps
```

**Comment by anshul-fitsib** [comment]
@Zaydme 

please update the plugin with Strapi 5

**Comment by Zaydme** [comment]
Thank you @matthewdickinson for getting this started.

**Comment by Zaydme** [comment]
[strapi-plugin-multi-select@2.0.0](https://www.npmjs.com/package/strapi-plugin-multi-select/v/2.0.0) with Strapi v5 support has been published, any feedback is appreciated.

**Pull request merged**
