### PR TITLE
allow usage of a default value

### PR DESCRIPTION
**Pull request by FlashThePlayer**
Little MR to allow the usage of the default value 
Credit goes to @matteocattelan for giving the code sample

### CODE REVIEW

**Review by dainius-zm — APPROVED** [review]

**Comment by FlashThePlayer** [comment]
@Zaydme ping? 
not sure if this repo is fully maintained 
If not I would just fork it but I would like to avoid this if possible

**Comment by dainius-zm** [comment]
I am looking for this feature release too, so it would be great to be able to merge it asap @Zaydme

**Comment by Zaydme** [comment]
I apologize but I do my best to keep up!

Thank you @FlashThePlayer for the contribution, and @matteocattelan for the idea.

I will be looking into this now, will test it and merge it and update the package.
You contributions are greatly appreciated 🙌🚀

**Comment by sam899** [comment]
@Zaydme any updates on this one? Thanks!

**Comment by aadelgrossi** [comment]
⬆️ 

Would love this feature implemented as well @Zaydme 

I have ran into [this issue](https://github.com/Zaydme/strapi-plugin-multi-country-select/issues/2) while using [strapi-plugin-multi-country-select](https://github.com/ChrisEbert/strapi-plugin-country-select) and using `strapi-plugin-multi-select` fixes this problem, and having default values would be highly desired for our use case.

**Comment by Zaydme** [comment]
closed in https://github.com/Zaydme/strapi-plugin-multi-select/commit/073af312d5bfba80ab5e005b0faa0b6631bc90c6
available in @2.1.0

Thank you!

**Pull request closed without merging**
